package com.example.chess;

public enum GameStatus {
    ACTIVE,
    CHECKMATE_BLACK_WIN,
    CHECKMATE_WHITE_WIN,
    STALEMATE_DRAW,
    INSUFFICIENT_MATERIAL_DRAW,
    DRAW_BY_REPETITION,
    RESIGNATION_BLACK_WIN,
    RESIGNATION_WHITE_WIN,
    TIMEOUT_WHITE_WIN,
    TIMEOUT_BLACK_WIN,
}
